### PR TITLE
Adding configuration and logic for using a named graph

### PR DESCRIPTION
**Pull request by ajs6f**
Using a constant BASE URI to resolve the relative URI `#ri`, an inelegant but straightforward technique.

### CODE REVIEW

**Comment by ajs6f** [comment]
I have no idea why `SparqlConnector` shows so many line deltas. It's just a change to add the appropriate config piece. Perhaps we have differing whitespace settings in IDEs?

**Comment by ddavis** [comment]
Don't know.  I checked Idea and its settings look correct.  And I visited pretty much all the files to change the package.  H'mmm.

**Comment by ajs6f** [comment]
Well, in a codebase this small, I'm not going to worry about it much. If it becomes a real pain in the neck, we can deal with it then.

**Comment by ddavis** [comment]
I am still going to check all the file and fix-em as needed.

**Comment by ajs6f** [comment]
Is there a set of SI-wide code standards? Or maybe, since SI-wide is rather a big bite, ORIS standards?

**Comment by ddavis** [comment]
We are working on it but it will be basically the same as the Duraspace/Fedora one.  There is definitely no SI-wide version.  We are pretty much starting up a shop from scratch.

**Comment by ajs6f** [comment]
"We are pretty much starting up a shop from scratch."

Ah, freedom! {grin}

**Pull request merged**
